### ISSUE TITLE
Feature request: Auto create SQL JOINS by holding Ctrl+click

### ISSUE THREAD

**Issue by nmystic22** [ernstc/SqlDataInspector#9]
Title of this says most of it. 
**Would it be possible to create basic joins and populate the results window by holding CTRL+LeftClick perhaps?** 
- Add an option in the settings for the extension to change what type of SQL JOIN is applied when you select multiple tables? 
- Error out when no relationship between keys exist?

**Comment by ernstc** [comment]
Hi @nmystic22 the initial idea was to remain as simple as possible, so that's why I have not thought to SQL JOINs until now, but it's a feature that can be investigated. 
So, the idea is that selecting more than one table, it should choose automatically the foreign key to use for the JOIN. It can be simple if there is only one foreign key between the selected tables. But if there are multiple FK, the result can include a lot of columns since it takes all of them.

**Comment by nmystic22** [comment]
I see the point there. I think the first version of the feature might allow for joins where there is only a single (or "obvious"?) FK between selections. Just that would be a huge win from my perspective. To maintain overall performance of the extension (which is amazing) I would not have a problem getting prompted with a "too many FK in selection" type of warning.

Alternatively, could there be a fourth window to the extension that shows other tables/views in the DB that have related FK's to the selection and do it that way? Perhaps that could be a second "output" window instead of something selectable (ie: you get to see a list of related tables or views to the one selected in addition to the actual data). That alone would be quite helpful.

**Comment by nmystic22** [comment]
I'll leave my comments up but don't want you to have an open "issue" that really is not an issue at all. Backlog item perhaps? ;) 

HUGE thx for adding functionality for views. Great idea with the checkboxes as well
